service: molab-datapoint-ls

provider:
  name: aws
  runtime: nodejs4.3
  region: eu-west-1
  profile: serverless-admin

functions:
  datapoint:
    handler: src/main/js/handler.datapoint
    events:
      - http:
          path: datapoint
          method: get

plugins:
  - serverless-mocha-plugin

