'use strict';

// tests for datapoint
// Generated by serverless-mocha-plugin

const mod = require('../../../src/main/js/handler.js');
const mochaPlugin = require('serverless-mocha-plugin');

const lambdaWrapper = mochaPlugin.lambdaWrapper;
const expect = mochaPlugin.chai.expect;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'datapoint' });

// describe('datapoint', () => {
//
//   before((done) => {
// //  lambdaWrapper.init(liveFunction); // Run the deployed lambda
//     done();
//   });
//
//   it('responses not empty', () => {
//     return wrapped.run({}).then((responses) => {
//       console.log(responses);
//       expect(responses).to.not.be.empty;
//     });
//   });
// });
